export const info = {
    name: 'yandex',
    icon: 'logo/yandex.svg',
};
// https://yandex.com/dev/translate/doc/en/concepts/api-overview
export enum Language {
    auto = '',
    ko = 'ko',
    en = 'en',
    ja = 'ja',
    zh_cn = 'zh',
    zh_tw = 'zh',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    nb_no = 'no',
    nn_no = 'no',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
}
